
<div class="row" style="margin-top:200px">
    <div class="col-md-4 content">
    		<form role="form">
    			<fieldset>
    				<h2 class="text-center">เข้าสู่ระบบ</h2>
    				<hr class="colorgraph">
    				<div class="form-group">
                <input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email Address">
    				</div>
    				<div class="form-group">
                <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password">
    				</div>
    				<span class="button-checkbox">
    					<button type="button" class="btn" data-color="info">Remember Me</button>
                <input type="checkbox" name="remember_me" id="remember_me" checked="checked" class="hidden">
    					<a href="" class="btn btn-link pull-right">Forgot Password?</a>
    				</span>
    				<hr class="colorgraph">
    				<div class="row">
    					<div class="col-md-12">
                <input type="submit" class="btn btn-lg btn-success btn-block" value="Login">
    				  </div>
            </div>
    			</fieldset>
    		</form>
    </div>
</div>
