<?php
  echo $this->tag->form(
    [
      "auth/checkLogin",
      "autocomplete" => "off",
      "class" => "form-horizontal"
    ]
  );
    ?>

<div class="row" style="margin-top:200px">
    <div class="col-md-4 content">
    		<form role="form">
    			<fieldset>
    				<h2 class="text-center">เข้าสู่ระบบ</h2>
    				<hr class="colorgraph">
    				<div class="form-group">
              <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" =>
  "fieldName","placeholder" => "อีเมลล์"]) ?>
                <!-- <input type="email" name="email" id="email" class="form-control input-lg" placeholder="อีเมลล์"> -->
    				</div>
    				<div class="form-group">
              <?php echo $this->tag->textField(["password", "size" => 30, "class" => "form-control", "id" =>
  "fieldName","placeholder" => "รหัสผ่าน"]) ?>
                <!-- <input type="password" name="password" id="password" class="form-control input-lg" placeholder="รหัสผ่าน"> -->
    				</div>

    				<hr class="colorgraph">
            <br>

    				<div class="text-center">
              <?php echo $this->tag->submitButton(["login", "class" => "btn btn-lg btn-success btn-block" ,"style" => "width:120px"]) ?>


              <!-- <input type="submit" class="btn btn-lg btn-success btn-block" value="Login" style="width:120px"> -->

            </div>
    			</fieldset>
    		</form>
    </div>
</div>
<?php echo $this->tag->endForm(); ?>
