
<style media="screen">
html {
  font-family: Lato, 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size: 14px;
}

h5 {
  font-size: 1.28571429em;
  font-weight: 700;
  line-height: 1.2857em;
  margin: 0;
}

.card {
  font-size: 1em;
  overflow: hidden;
  padding: 0;
  border: none;
  border-radius: .28571429rem;
  box-shadow: 0 1px 3px 0 #d4d4d5, 0 0 0 1px #d4d4d5;
}

.card-block {
  font-size: 1em;
  position: relative;
  margin: 0;
  padding: 1em;
  border: none;
  border-top: 1px solid rgba(34, 36, 38, .1);
  box-shadow: none;
}

.card-img-top {
  display: block;
  width: 100%;
  height: auto;
}

.card-title {
  font-size: 1.28571429em;
  font-weight: 700;
  line-height: 1.2857em;
}

.card-text {
  clear: both;
  margin-top: .5em;
  color: rgba(0, 0, 0, .68);
}

.card-footer {
  font-size: 1em;
  position: static;
  top: 0;
  left: 0;
  max-width: 100%;
  padding: .75em 1em;
  color: rgba(0, 0, 0, .4);
  border-top: 1px solid rgba(0, 0, 0, .05) !important;
  background: #fff;
}

.card-inverse .btn {
  border: 1px solid rgba(0, 0, 0, .05);
}

.profile {
  position: absolute;
  top: -40px;
  display: inline-block;
  overflow: hidden;
  box-sizing: border-box;
  width: 60px;
  height: 60px;
  margin: 0;
  border: 1px solid #fff;
  border-radius: 50%;
}

.profile-avatar {
  display: block;
  width: 100%;
  height: auto;
  border-radius: 50%;
}

.profile-inline {
  position: relative;
  top: 0;
  display: inline-block;
}

.profile-inline ~ .card-title {
  display: inline-block;
  margin-left: 4px;
  vertical-align: top;
}

.text-bold {
  font-weight: 700;
}

.meta {
  font-size: 1em;
  color: rgba(0, 0, 0, .4);
}

.meta a {
  text-decoration: none;
  color: rgba(0, 0, 0, .4);
}

.meta a:hover {
  color: rgba(0, 0, 0, .87);
}
</style>

<div class="container">
        <div class="row">
          <?php for ($i = 0 ; $i<2 ;$i++): ?>
          <div class="col-sm-6 col-md-4 col-lg-4 mt-4">
              <div class="card card-inverse card-info">

                  <img class="card-img-top" src="<?=$this->url->get('img/activity/dotnet.jpg') ?>">
                  <div class="card-block">
                      <figure class="profile">
                          <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" width="30px" class="profile-avatar" alt="">
                      </figure>
                      <h4 class="card-title mt-3">จัดอบรม .NET for Web-based Application สำหรับนักศึกษาชั้นปีที่ 2</h4>
                      <div class="meta">
                          <a>อาจารย์ ดร.จิตติมา ศังขมณี</a>
                      </div>
                      <div class="card-text">
                        วันที่ 29-30 เม.ย. 2560
                      </div>
                  </div>
                  <div class="card-footer">
                      <small>Last updated 3 mins ago</small>
                      <button class="btn btn-secondary float-right btn-sm">show</button>
                  </div>
              </div>
          </div>
        <?php endfor; ?>
        <div class="col-sm-6 col-md-4 col-lg-4 mt-4">
            <div class="card card-inverse card-info">

                <img class="card-img-top" src="<?=$this->url->get('img/activity/waipa.jpg') ?>">
                <div class="card-block">
                    <figure class="profile">
                        <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" class="profile-avatar" alt="">
                    </figure>
                    <h4 class="card-title mt-3">ค่ายพัฒนาซอฟต์แวร์ "SWE ไหวป่ะ"</h4>
                    <div class="meta">
                        <a>อาจารย์ ดร.จิตติมา ศังขมณี</a>
                    </div>
                    <div class="card-text">
                      วันที่ 29-30 เม.ย. 2560
                    </div>
                </div>
                <div class="card-footer">
                    <small>Last updated 3 mins ago</small>
                    <button class="btn btn-secondary float-right btn-sm">show</button>
                </div>
            </div>
        </div>
        </div>
</div>
