
<div class="container">
    <div class="row">
      <?php foreach ($page->items as $act): ?>
        <div class="col-sm-6 col-md-4 col-lg-4 mt-4">
            <div class="card card-inverse card-info">

                <img class="card-img-top" src="<?=$this->url->get('img/activity/dotnet.jpg') ?>">
                <div class="card-block">
                    <figure class="profile">
                        <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" width="30px" class="profile-avatar" alt="">
                    </figure>

                    <h4 class="card-title mt-3"><?=$act->name; ?></h4>
                    <div class="meta">
                        <a><?=$act->Teacher->prefix;?>&nbsp;&nbsp;<?=$act->Teacher->Firstname; ?>&nbsp;&nbsp;<?=$act->Teacher->Lastname; ?></a>
                    </div>
                    <div class="card-text">
                      วันเริ่มกิจกรรม : <?=$act->StartDate; ?> <br> วันสิ้นสุดกิจกรรม : <?=$act->EndDate; ?>
                    </div>
                </div>
                <div class="card-footer">
                    <small>Last updated 3 mins ago</small>
                    <?= $this->tag->linkTo(["activity/show/10", "เพิ่มเติม", "class" => "btn btn-secondary float-right btn-sm"]) ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>
