
<div class="container">
  <div class="page-header" style="margin-top:40px">
    <h1 class="mb-4 mr-sm-4 mb-sm-0">รายชื่อกิจกรรม <?php echo $this->tag->linkto(["manage/activityadd", "class" => "btn btn-outline-success btn-secondary pull-right","เพิ่มกิจกรรม"]) ?></h1>
  </div>
  <br>
  <form>
    <div class="input-group">
      <?php echo $this->tag->textField(["s", "class" => "form-control" , "placeholder" => "ค้นหาจากชื่อกิจกรรม , ปี่ที่จัดกิจกรรม"]) ?>
      <span class="input-group-btn">
        <?php echo $this->tag->submitButton(["ค้นหา", "class" => "btn btn-outline-primary btn-secondary"]) ?>
      </span>
    </div>
  </form>
    <table class="table table-striped" style="margin-top:20px">
      <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center">ชื่อกิจกรรม</th>
          <th class="text-center">นักศึกษาทั้งหมด</th>
          <th class="text-center">นักศึกษาที่เข้าร่วม</th>
          <th class="text-center">ดำเนินการ</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($page->items as $act): ?>
          <tr>
            <th class="text-center" scope="row">1</th>
            <td class="text-center">ค่ายอมรม Scrum Framwork 2017</td>
            <td class="text-center">100</td>
            <td class="text-center">78</td>
            <td class="text-center"><?php echo $this->tag->linkto(["manage/activityedit", "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
            <?php echo $this->tag->linkto(["manage/activitystudent", "class" => "btn btn-success btn-sm","ผู้เข้าร่วม"]) ?></td>
          </tr>
          <tr>
            <th class="text-center" scope="row">1</th>
            <td class="text-center">ค่ายอมรม Scrum Framwork 2017</td>
            <td class="text-center">100</td>
            <td class="text-center">78</td>
            <td class="text-center"><?php echo $this->tag->linkto(["manage/activityedit", "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
            <?php echo $this->tag->linkto(["manage/activitystudent", "class" => "btn btn-success btn-sm","ผู้เข้าร่วม"]) ?></td>
          </tr>
          <tr>
            <th class="text-center" scope="row">1</th>
            <td class="text-center">ค่ายอมรม Scrum Framwork 2017</td>
            <td class="text-center">100</td>
            <td class="text-center">78</td>
            <td class="text-center"><?php echo $this->tag->linkto(["manage/activityedit", "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
            <?php echo $this->tag->linkto(["manage/activitystudent", "class" => "btn btn-success btn-sm","ผู้เข้าร่วม"]) ?></td>
          </tr>
          <tr>
            <th class="text-center" scope="row">1</th>
            <td class="text-center">ค่ายอมรม Scrum Framwork 2017</td>
            <td class="text-center">100</td>
            <td class="text-center">78</td>
            <td class="text-center"><?php echo $this->tag->linkto(["manage/activityedit", "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
            <?php echo $this->tag->linkto(["manage/activitystudent", "class" => "btn btn-success btn-sm","ผู้เข้าร่วม"]) ?></td>
          </tr>

        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
