
<?php
  echo $this->tag->form(
      [
          "manage/activityadd",
          "autocomplete" =>"off",
          "class" => "form-horizontal"
      ]
);
?>
<div class="container">
    <form class="form-horizontal" role="form" method="POST" action="/register">
      <ul class="errorMessages"></ul>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6" style="margin-top:50px">
                <h2>สร้างข้อมูลกิจกรรม</h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">ชื่อกิจกรรม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-laptop"></i></div>
                        <?=$this->tag->textField( [ "name", "class" => "form-control","placeholder" => "ชื่อกิจกรรม", "required"=>"","autofocus"=>""] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put name validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">รายละเอียด</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-comment"></i></div>
                        <?=$this->tag->textarea( [ "activitydetail", "class" => "form-control","placeholder" => "รายละเอียด", "required"=>""] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">

                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive" style="margin-top:20px">
                <label for="date">วัน/เดือน/ปี ที่จัดกิจกรรม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-calendar"></i></div>
                        <?=$this->tag->dateField( [ "Years", "class" => "form-control", "required"=>""] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="file">รูปกิจกรรม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-picture-o"></i></div>
                        <?=$this->tag->fileField( [ "file", "class" => "form-control","placeholder" => "file" , "accept"=>"image/png, image/jpeg, image/gif"] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">ชั้นปีที่เข้าร่วม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0" style="margin-top:8px">
                      <fieldset class="form-group">
                        <div class="form-check">
                          <label class="form-check-label">
                              <input type="checkbox" class="form-check-input" name="optionsRadios" id="optionsRadios1" value="option1">
                              นักศึกษาชั้นปีที่ 1
                          </label>
                          &nbsp;&nbsp;
                          <label class="form-check-label">
                              <input type="checkbox" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                              นักศึกษาชั้นปีที่ 2
                          </label>
                          &nbsp;&nbsp;
                          <label class="form-check-label">
                              <input type="checkbox" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                              นักศึกษาชั้นปีที่ 3
                          </label>
                          &nbsp;&nbsp;
                          <label class="form-check-label">
                              <input type="checkbox" class="form-check-input" name="optionsRadios" id="optionsRadios2" value="option2">
                              นักศึกษาชั้นปีที่ 4
                          </label>
                        </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
          <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                <?php echo $this->tag->submitButton(["บันทึกการจัดกิจกรรม", "class" => "btn btn-success"]) ?>
              </div>
          </div>
    </form>

    <!--
    <div class="row">
        <div class="col-md-3 field-label-responsive" style="margin-top:3px">
            <label for="password">ชั้นปีที่เข้าร่วม</label>
        </div>
        <div class="col-md-6">
            <div class="form-inline">
                <div class="input-group mb-2 mr-sm-2 mb-sm-0" style="margin-top:5px">
                  <div class="form-group">
                    <select class="form-control" id="exampleSelect1">
                      <option>นักศึกษาทุกชั้นปี</option>
                      <option>นักศึกษาชั้นปีที่ 1</option>
                      <option>นักศึกษาชั้นปีที่ 2</option>
                      <option>นักศึกษาชั้นปีที่ 3</option>
                      <option>นักศึกษาชั้นปีที่ 4</option>
                    </select>
                  </div>
                </div>
            </div>
        </div>
    </div>
  -->
</div><?php echo $this->tag->endForm(); ?>
