
<div class="container">
  <div class="page-header" style="margin-top:40px">
    <h1 class="mb-4 mr-sm-4 mb-sm-0">รายชื่อกิจกรรม <?php echo $this->tag->linkto(["manage/activityadd", "class" => "btn btn-outline-success btn-secondary pull-right","เพิ่มกิจกรรม"]) ?></h1>
  </div>
  <br>
  <form>
    <div class="input-group">
      <?php echo $this->tag->textField(["s", "class" => "form-control" , "placeholder" => "ค้นหาจากชื่อกิจกรรม , ปี่ที่จัดกิจกรรม"]) ?>
      <span class="input-group-btn">
        <?php echo $this->tag->submitButton(["ค้นหา", "class" => "btn btn-outline-primary btn-secondary"]) ?>
      </span>
    </div>
  </form>
    <table class="table table-striped" style="margin-top:20px">
      <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center">ชื่อกิจกรรม</th>
          <th class="text-center">ประเภทกิจกรรม</th>
          <th class="text-center">อาจารย์ที่ปรึกษา</th>
          <th class="text-center">ดำเนินการ</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($page->items as $act): ?>
          <tr>
            <th class="text-center" scope="row">1</th>
            <td class="text-center"><?=$act->name?></td>
            <td class="text-center"><?=$act->Type->name?></td>
            <td class="text-center"><?=$act->Teacher->prefix?> <?=$act->Teacher->Firstname?> <?=$act->Teacher->Lastname?> </td>
            <td class="text-center">
              <?php echo $this->tag->linkto(["manage/activityedit/".$act->id, "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
              <?php echo $this->tag->linkto(["manage/activitystudent/".$act->id, "class" => "btn btn-success btn-sm","ผู้เข้าร่วม (".$act->JoinActivity->count().") "]) ?>
              <?php echo $this->tag->linkto(["manage/activitydelete/".$act->id, "class" => "btn btn-danger btn-sm","ลบ"]) ?>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
