
<?php
  echo $this->tag->form(
      [
          "manage/activityupdate/".$id,
          "autocomplete" =>"off",
          "class" => "form-horizontal"
      ]
);
?>
<div class="container">
    <form class="form-horizontal" role="form" method="POST" action="/register">
      <ul class="errorMessages"></ul>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6" style="margin-top:50px">
                <h2>สร้างข้อมูลกิจกรรม</h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">ชื่อกิจกรรม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-laptop"></i></div>
                        <?=$this->tag->textField( [ "name", "class" => "form-control","placeholder" => "ชื่อกิจกรรม", "required"=>"","autofocus"=>""] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put name validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">ประเภทกิจกรรม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-laptop"></i></div>
                        <?php echo $this->tag->selectStatic(
                          [
                            "type_id", "class" => "form-control" ,$type_id
                          ]
                        );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put name validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">รายละเอียด</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-comment"></i></div>
                        <?=$this->tag->textarea( [ "activitydetail", "class" => "form-control","placeholder" => "รายละเอียด", "required"=>""] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">

                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive" style="margin-top:20px">
                <label for="date">วันเริ่มกิจกรรม วัน/เดือน/ปี</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-calendar"></i></div>
                        <?=$this->tag->dateField( [ "Yearstart", "class" => "form-control", "required"=>""] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive" style="margin-top:20px">
                <label for="date">วันสิ้นสุดกิจกรรม วัน/เดือน/ปี</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-calendar"></i></div>
                        <?=$this->tag->dateField( ["Yearend", "class" => "form-control", "required"=>""] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive" style="margin-top:3px">
                <label for="password">ภาคการศึกษา</label>
            </div>
            <div class="col-md-6">
                <div class="form-inline">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0" style="margin-top:5px">
                      <div class="form-group">
                        <?php echo $this->tag->selectStatic(
                          [
                            "semester", "class" => "form-control" ,
                            [
                              "1" => "ภาคการศึกษาที่ 1",
                              "2" => "ภาคการศึกษาที่ 2",
                              "3" => "ภาคการศึกษาที่ 3",
                            ]
                          ]
                        );?>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <label for="password">ปีการศึกษา</label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <?=$this->tag->textField( [ "Year", "class" => "form-control","placeholder" => "ปีการศึกษา", "required"=>""] );?>
                      </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive" style="margin-top:17px">
                <label for="file">อาจารย์ผู้รับผิดชอบ</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0" style="margin-top:15px">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                        <?php echo $this->tag->selectStatic(
                          [
                            "teacher_id", "class" => "form-control" , $users_id
                          ]
                        );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive" style="margin-top:17px">
                <label for="file">สถานที่จัดกิจกรรม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0" style="margin-top:15px">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-home"></i></div>
                        <?php echo $this->tag->selectStatic(
                          [
                            "location_id", "class" => "form-control" ,$location_id
                          ]
                        );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive" style="margin-top:17px">
                <label for="file">รูปกิจกรรม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0" style="margin-top:15px">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-picture-o"></i></div>
                        <?=$this->tag->fileField( [ "file", "class" => "form-control","placeholder" => "file" , "accept"=>"image/png, image/jpeg, image/gif"] );?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">ปีการศึกษาที่เข้าร่วม</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0" style="margin-top:8px">
                      <fieldset class="form-group">
                        <div class="form-check">
                          <?php foreach ($years as $year): ?>
                            <label class="form-check-label">
                                <input type="checkbox" class="form-check-input" name="years[]" id="optionsRadios1" value="<?=$year?>" >
                                นักศึกษาปีการศึกษา <?=$year?>
                            </label>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                          <?php endforeach; ?>
                        </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
          <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                <?php echo $this->tag->submitButton(["บันทึก", "class" => "btn btn-success"]) ?>
              </div>
          </div>
    </form>

    <!--

  -->
</div><?php echo $this->tag->endForm(); ?>
