<div class="comtainer">
  <div class="jumbotron jumbotron-fluid" style="margin-top:40px">
    <div class="container">
      <h1 class="display-4 text-center">ยินดีต้อนรับเข้าสู่ "ระบบจัดการกิจกรรม"</h1>
      <p class="lead text-center">This is a modified jumbotron that occupies the entire horizontal space of its parent.</p>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
  <div class="card" style="margin-top:30px">
    <div class="card-header card-info text-center">
      <h3>กิจกรรมทั้งหมด</h3>
    </div>
    <div class="card-block">
      <blockquote class="card-blockquote">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
      </blockquote>
    </div>
    <div class="card-footer text-muted text-right">
    <?php echo $this->tag->linkto(["manage/activitysearch", "class" => "btn btn-outline-info btn-secondary pull-right","ดูเพิ่มเติม"]) ?>
  </div>
  </div>
  </div>
  <div class="col-md-4">
  <div class="card" style="margin-top:30px">
    <div class="card-header card-success text-center">
      <h3>อาจารย์ทั้งหมด</h3>
    </div>
    <div class="card-block">
      <blockquote class="card-blockquote">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
      </blockquote>
    </div>
    <div class="card-footer text-muted text-right">
    <?php echo $this->tag->linkto(["manage/teachersearch", "class" => "btn btn-outline-success btn-secondary pull-right","ดูเพิ่มเติม"]) ?>
  </div>
  </div>
  </div>
  <div class="col-md-4">
  <div class="card" style="margin-top:30px">
    <div class="card-header card-warning text-center">
      <h3>นักศึกษาทั้งหมด</h3>
    </div>
    <div class="card-block">
      <blockquote class="card-blockquote">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
        <footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
      </blockquote>
    </div>
    <div class="card-footer text-muted text-right">
    <?php echo $this->tag->linkto(["manage/studentsearch", "class" => "btn btn-outline-warning btn-secondary pull-right","ดูเพิ่มเติม"]) ?>
  </div>
  </div>
  </div>
</div>
