
<div class="container">
  <div class="page-header" style="margin-top:40px">
    <h1 class="mb-4 mr-sm-4 mb-sm-0">รายการสถานที่ <?php echo $this->tag->linkto(["manage/locationadd", "class" => "btn btn-outline-success btn-secondary pull-right","เพิ่มสถานที่"]) ?></h1>
  </div>
  <br>
  <form>
    <div class="input-group">
      <?php echo $this->tag->textField(["s", "class" => "form-control" , "placeholder" => "ค้นหาจากชื่อสถานที่ , รายละเอียดสถานที่"]) ?>
      <span class="input-group-btn">
        <?php echo $this->tag->submitButton(["ค้นหา", "class" => "btn btn-outline-primary btn-secondary"]) ?>
      </span>
    </div>
  </form>
    <table class="table table-striped" style="margin-top:20px">
      <thead>
        <tr>
          <th class="text-center">ชื่อสถานที่</th>
          <th class="text-center">รายละเอียด</th>
          <th class="text-center">ดำเนินการ</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($page->items as $act): ?>
          <tr>
            <th class="text-center" scope="row"><?=$act->name; ?></th>
            <td class="text-center"><?=$act->room?></td>
            <td class="text-center">
              <?php echo $this->tag->linkto(["manage/locationedit/".$act->id, "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
              <?php echo $this->tag->linkto(["manage/locationdelete/".$act->id, "class" => "btn btn-danger btn-sm","ลบ"]) ?>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    <div style="width:100%;">
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item">
            <?php echo $this->tag->linkto(["manage/locationsearch".(isset($s)?"/?s={$s}":""), "class" => "page-link","< หน้าแรก"]) ?>
          </li>
          <?php if ($page->before != $page->current): ?>
          <li class="page-item">
            <?php echo $this->tag->linkto(["manage/locationsearch/?".(isset($s)?"s={$s}&":"")."page=".$page->before, "class" => "page-link",$page->before]) ?>
          </li>
          <?php endif; ?>
          <li class="page-item disabled"><a class="page-link" href="#"><?=$page->current?></a></li>
          <?php if ($page->next != $page->current && $page->next > 0 ): ?>
          <li class="page-item">
            <?php echo $this->tag->linkto(["manage/locationsearch/?".(isset($s)?"s={$s}&":"")."page=".$page->next, "class" => "page-link",$page->next]) ?>
          </li>
          <?php endif; ?>
          <li class="page-item">
            <?php echo $this->tag->linkto(["manage/locationsearch/?".(isset($s)?"s={$s}&":"")."page=".$page->last, "class" => "page-link","สุดท้าย >>"]) ?>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>
