
<div class="container">
  <div class="page-header" style="margin-top:40px">
    <h1 class="mb-4 mr-sm-4 mb-sm-0">รายการสถานที่ <?php echo $this->tag->linkto(["manage/locationadd", "class" => "btn btn-outline-success btn-secondary pull-right","เพิ่มสถานที่"]) ?></h1>
  </div>
  <br>
  <form>
    <div class="input-group">
      <?php echo $this->tag->textField(["s", "class" => "form-control" , "placeholder" => "ค้นหาจากชื่อสถานที่ , รายละเอียดสถานที่"]) ?>
      <span class="input-group-btn">
        <?php echo $this->tag->submitButton(["ค้นหา", "class" => "btn btn-outline-primary btn-secondary"]) ?>
      </span>
    </div>
  </form>
    <table class="table table-striped" style="margin-top:20px">
      <thead>
        <tr>
          <th class="text-center">ชื่อสถานที่</th>
          <th class="text-center">รายละเอียด</th>
          <th class="text-center">ดำเนินการ</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($page->items as $act): ?>
          <tr>
            <th class="text-center" scope="row"><?=$act->name; ?></th>
            <td class="text-center"><?=$act->room?></td>
            <td class="text-center">
              <?php echo $this->tag->linkto(["manage/locationedit/".$act->id, "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
              <?php echo $this->tag->linkto(["manage/locationdelete/".$act->id, "class" => "btn btn-danger btn-sm","ลบ"]) ?>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
