
<?php $this->flashSession->output() ?>
<style media="screen">
@media(min-width: 768px) {
.field-label-responsive {
  padding-top: .5rem;
  text-align: right;
}
}
</style>
<?php
echo $this->tag->form(
[
"manage/register",
"autocomplete" =>"off",
"class" => "form-horizontal"
]
);
?>
<br>
<div class="container">
    <form class="form-horizontal" role="form" method="POST" action="/register">
      <ul class="errorMessages"></ul>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <h2>ลงทะเบียน</h2>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">รหัสประจำตัว</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-laptop"></i></div>
                        <input type="text" name="id" class="form-control" id="id" placeholder="ID" required autofocus>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put name validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="password">รหัสผ่าน</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-key"></i></div>
                        <input type="password" name="password" class="form-control" id="password" placeholder="Password" required>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">

                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="name">ชื่อจริง</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-user"></i></div>
                        <input type="text" name="fname" class="form-control" id="firstname" placeholder="Firstname" required autofocus>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">

                        </span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 field-label-responsive">
                <label for="email">นามสกุล</label>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-signal"></i></div>
                        <input type="text" name="lname" class="form-control" id="lastname" placeholder="Lastname" required autofocus>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-control-feedback">
                        <span class="text-danger align-middle">
                            <!-- Put e-mail validation error messages here -->
                        </span>
                </div>
            </div>
        </div>
          <div class="row">
              <div class="col-md-3 field-label-responsive">
                  <label for="exampleSelect1">กรุณาเลือกสถานะ</label>
              </div>
              <div class="col-md-6">
                  <div class="form-group">
                      <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                        <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-star-o"></i></div>
                        <select class="form-control" id="exampleSelect1">
                          <option>นักศึกษา</option>
                          <option>อาจารย์</option>
                          <option>อาจารย์และผู้ดูแลระบบ</option>
                        </select>
                      </div>
                  </div>
              </div>
            </div>
            <div class="row">
                <div class="col-md-3 field-label-responsive">
                    <label for="email">ปีการศึกษา</label>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                            <div class="input-group-addon" style="width: 2.6rem"><i class="fa fa-calendar"></i></div>
                            <input type="text" name="lname" class="form-control" id="lastname" placeholder="ปีการศึกษา" required autofocus>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-control-feedback">
                            <span class="text-danger align-middle">
                                <!-- Put e-mail validation error messages here -->
                            </span>
                    </div>
                </div>
            </div>
          <div class="row">
              <div class="col-md-3"></div>
              <div class="col-md-6">
                  <button type="submit" class="btn btn-success"><i class="fa fa-user-plus"></i> ยืนยันการลงทะเบียน</button>
              </div>
          </div>
    </form>
</div>
<?php echo $this->tag->endForm(); ?>
