<?php $this->flashSession->output() ?>
<div class="row">
<nav>
<ul class="pager">
<li class="previous"><?php echo $this->tag->linkTo(["student/search", "Go Back"]) ?></li>
</ul>
</nav>
</div>
<div class="page-header">
<h1>
Register new user
</h1>
</div>
<?php
echo $this->tag->form(
[
"user/saveRegister",
"autocomplete" =>"off",
"class" => "form-horizontal"
]
);
?>
<div class="form-group">
<label for="fieldName" class="col-sm-2 control-label">Login</label>
<div class="col-sm-4">
<?php echo $this->tag->textField(["login", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
</div>
</div>
<div class="form-group">
<label for="fieldName" class="col-sm-2 control-label">Password</label>
<div class="col-sm-4">
<?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
</div>
</div>


<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<?php echo $this->tag->submitButton(["Register", "class" => "btn btn-default"]) ?>
</div>
</div>
<?php echo $this->tag->endForm(); ?>
