<?php use Phalcon\Tag; ?>
<?php $this->flashSession->output() ?>

<div class="container">

      <div class="page-header" style="margin-top:40px">
        <h1 class="mb-4 mr-sm-4 mb-sm-0">รายชื่อนักศึกษา <?php echo $this->tag->linkto(["manage/studentadd", "class" => "btn btn-outline-success btn-secondary pull-right","เพิ่มนักศึกษา"]) ?></h1>
      </div>
      <br>
      <form>
        <div class="input-group">
          <?php echo $this->tag->textField(["s", "class" => "form-control" , "placeholder" => "ค้นหาชื่อ,นามสกุล,ปี่ที่เข้าศึกษา"]) ?>
          <span class="input-group-btn">
            <?php echo $this->tag->submitButton(["ค้นหา", "class" => "btn btn-outline-primary btn-secondary"]) ?>
          </span>
        </div>
      </form>
      <table class="table table-striped" style="margin-top:10px">
        <thead>
          <tr>
            <th class="text-center">รหัสนักศึกษา</th>
            <th class="text-center">ชื่อ</th>
            <th class="text-center">นามสกุล</th>
            <th class="text-center">ปีที่เข้าศึกษา</th>
            <th class="text-center">ดำเนินการ</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($page->items as $act): ?>
            <tr>
              <th class="text-center" scope="row"><?=$act->username; ?></th>
              <td class="text-center"><?=$act->Firstname?></td>
              <td class="text-center"><?=$act->Lastname?></td>
              <td class="text-center"><?=$act->Years?></td>
              <td class="text-center">
                <?php echo $this->tag->linkto(["manage/studentedit/".$act->id, "class" => "btn btn-info btn-sm","แก้ไข"]) ?>
                <?php echo $this->tag->linkto(["manage/studentdelete/".$act->id, "class" => "btn btn-danger btn-sm","ลบ"]) ?>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
      <div style="width:100%;">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <li class="page-item">
              <?php echo $this->tag->linkto(["manage/studentsearch".(isset($s)?"/?s={$s}":""), "class" => "page-link","< หน้าแรก"]) ?>
            </li>
            <?php if ($page->before != $page->current): ?>
            <li class="page-item">
              <?php echo $this->tag->linkto(["manage/studentsearch/?".(isset($s)?"s={$s}&":"")."page=".$page->before, "class" => "page-link",$page->before]) ?>
            </li>
            <?php endif; ?>
            <li class="page-item disabled"><a class="page-link" href="#"><?=$page->current?></a></li>
            <?php if ($page->next != $page->current && $page->next > 0 ): ?>
            <li class="page-item">
              <?php echo $this->tag->linkto(["manage/studentsearch/?".(isset($s)?"s={$s}&":"")."page=".$page->next, "class" => "page-link",$page->next]) ?>
            </li>
            <?php endif; ?>
            <li class="page-item">
              <?php echo $this->tag->linkto(["manage/studentsearch/?".(isset($s)?"s={$s}&":"")."page=".$page->last, "class" => "page-link","สุดท้าย >>"]) ?>
            </li>
          </ul>
        </nav>
      </div>
</div>
