<div class="row">
<nav>
<ul class="pager">

</ul>
</nav>
</div>
<div class="page-header">
  <h1>
    สร้างข้อมูลนักศึกษา
  </h1>
</div>
<?php
  echo $this->tag->form(
      [
          "student/create",
          "autocomplete" =>"off",
          "class" => "form-horizontal"
      ]
);
?>
<div class="form-group">
  <label for="fieldName" class="col-sm-2 control-label">รหัสนักศึกษา</label>
  <div class="col-sm-10">
      <?php echo $this->tag->textField(["stdid", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
    </div>
</div>
<div class="form-group">
  <label for="fieldName" class="col-sm-2 control-label">ชื่อ</label>
  <div class="col-sm-10">
      <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
  </div>
</div>
  <label for="fieldName" class="col-sm-2 control-label">นามสกุล</label>
<div class="col-sm-10">
      <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
</div>

<div class="form-group">
    <div class="col-sm-10">
    <label for="exampleSelect1">ชั้นปี</label>
    <select class="form-control" id="exampleSelect1">
      <option>ชั้นปีที่ 1</option>
        <option>ชั้นปีที่ 2</option>
          <option>ชั้นปีที่ 3</option>
            <option>ชั้นปีที่ 4</option>
      </select>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
      <?php echo $this->tag->submitButton(["สร้าง", "class" => "btn btn-default"]) ?>
  </div>
</div>
<?php echo $this->tag->endForm(); ?>
