<div class="row">
<nav>
<ul class="pager">

</ul>
</nav>
</div>
<div class="page-header">
  <h1>
      แก้ไขข้อมูลนักศึกษา
    </h1>
</div>
<?php
  echo $this->tag->form(
    [
      "manage/studentedit",
      "autocomplete" =>"off",
      "class" => "form-horizontal"
    ]
);
?>

<div class="form-group">
<label for="fieldName" class="col-sm-2 control-label">ID</label>
<div class="col-sm-10">
  <?php echo $this->tag->textField(["stdid", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
</div>
</div>
<div class="form-group">
<label for="fieldName" class="col-sm-2 control-label">ชื่อ</label>
<div class="col-sm-10">
  <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
</div>
</div>
<label for="fieldName" class="col-sm-2 control-label">นามสกุล</label>
<div class="col-sm-10">
  <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" =>"fieldName"]) ?>
</div>

<div class="form-group">
    <div class="col-sm-10">
    <label for="exampleSelect1">ตำแหน่ง</label>
    <select class="form-control" id="exampleSelect1">
      <option>อาจารย์(ผู้ดูแลระบบ)</option>
      <option>อาจารย์</option>
      </select>
  </div>
</div>

<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">
<?php echo $this->tag->submitButton(["สร้าง", "class" => "btn btn-default"]) ?>
</div>
</div>
<?php echo $this->tag->endForm(); ?>
