<?php use Phalcon\Tag; ?>
<?php $this->flashSession->output() ?>

<br>
<?= $this->tag->submitButton(["Search","class"=>"btn btn-info"]); ?>

<table class="table">
  <thead class="thead-default">
<div class="page-header">
<br>
<h1>รายชื่อนักศึกษา</h1>
</div>

<table class="table table-striped" border="1">
  <thead>
    <tr>
      <th>Id</th>
      <th>ชื่อ</th>
      <th>นามสกุล</th>
      <th>ชั้นปี</th>
      <th>แก้ไข</th>
      <th>ลบ</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Thasawat</td>
      <td>Rattanaphan</td>
      <td>Admin</td>
      <td><button type="button" class="btn btn-info">แก้ไข</button></td>
      <td><button type="button" class="btn btn-danger">ลบ</button></td>

    </tr>
    <?php foreach ($page->items as $act): ?>
      <tr>
        <th scope="row"><?=$act->id; ?></th>
        <td><?=$act->Firstname?></td>
        <td><?=$act->Lastname?></td>
        <td><?=$act->Years?></td>
        <td><button type="button" class="btn btn-info">แก้ไข</button></td>
        <td><button type="button" class="btn btn-danger">ลบ</button></td>

      </tr>

    <?php endforeach; ?>
  </tbody>
</table>
