  <div class="container">
        <div class="card mt-4">
            <div class="crop">
              <img class="card-img-top " src="<?=$this->url->get('img/activity/dotnet.jpg') ?>">
            </div>
            <div class="card-block">
                <figure class="profile">
                    <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" width="30px" class="profile-avatar" alt="">
                </figure>
                <h4 class="card-title mt-3"><?=$activity->name; ?></h4>
                <div class="meta">
                  <a href="<?=$this->url->get('user/profile/'.$activity->Teacher->id)?>"><?=$activity->Teacher->prefix;?>&nbsp;&nbsp;<?=$activity->Teacher->Firstname; ?>&nbsp;&nbsp;<?=$activity->Teacher->Lastname; ?></a>
                </div>
                <div class="card-text">
                  <ul class="mbm_social">
                  	<li><a class="social-facebook" href="#">
                  		<i class="fa fa-facebook"><small>facebook</small></i>

                  		<div class="tooltip"><span>facebook</span></div>
                  		</a>
                  	</li>
                  	<li><a class="social-twitter" href="#">
                  		<i class="fa fa-twitter"><small>Twitter</small></i>
                  		<div class="tooltip"><span>Twitter</span></div>
                  		</a>
                  	</li>
                  	<li><a class="social-google-plus" href="#">
                  		<i class="fa fa-google-plus"><small>google +</small></i>
                  		<div class="tooltip"><span>google</span></div>
                  		</a>
                  	</li>
                  	<li><a class="social-linkedin" href="#">
                  		<i class="fa  fa-linkedin"><small>linkedin</small></i>
                  		<div class="tooltip"><span>linkedin</span></div>
                  		</a>
                  	</li>
                  </ul>
                    <?=$activity->Datail; ?>
                </div>
            </div>
            <div class="card-footer">
                <small><?=date("วันที่ d เดือน m  ปี Y",strtotime($activity->StartDate))?> ถึง <?=date("วันที่ d เดือน m  ปี Y",strtotime($activity->EndDate))?></small>
                <button type="button" class="btn btn-sm btn-outline-primary float-right" data-toggle="modal" data-target="#myModal">จำนวนผู้เข้าร่วม 13/21 คน</button>



                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">รายชื่อผู้เข้าร่วม</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <?php for ($i=0; $i < 10; $i++) {
                          ?>
                           <p> <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" class="" style="width:20px;"> หฤษฎ์ คงทอง <small class="text-success">เข้าร่วม</small></p>
                          <?php
                        } ?>
                        <p>หฤษฎ์ คงทอง <small class="text-danger">ไม่เข่าร่วม</small></p>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- end model -->

            </div>
        </div>
    </div>

</div>
