<div class="container">
              <div class="card mt-4">
                  <div class="crop">
                    <img class="card-img-top " src="<?=$this->url->get('img/activity/dotnet.jpg') ?>">
                  </div>
                  <div class="card-block">
                      <figure class="profile">
                          <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" width="30px" class="profile-avatar" alt="">
                      </figure>
                      <h4 class="card-title mt-3">จัดอบรม .NET for Web-based Application สำหรับนักศึกษาชั้นปีที่ 2</h4>
                      <div class="meta">
                          <a>อาจารย์ ดร.จิตติมา ศังขมณี</a>
                      </div>
                      <div class="card-text">
                        <ul class="mbm_social">
                        	<li><a class="social-facebook" href="#">
                        		<i class="fa fa-facebook"><small>facebook</small></i>

                        		<div class="tooltip"><span>facebook</span></div>
                        		</a>
                        	</li>
                        	<li><a class="social-twitter" href="#">
                        		<i class="fa fa-twitter"><small>Twitter</small></i>
                        		<div class="tooltip"><span>Twitter</span></div>
                        		</a>
                        	</li>
                        	<li><a class="social-google-plus" href="#">
                        		<i class="fa fa-google-plus"><small>google +</small></i>
                        		<div class="tooltip"><span>google</span></div>
                        		</a>
                        	</li>
                        	<li><a class="social-linkedin" href="#">
                        		<i class="fa  fa-linkedin"><small>linkedin</small></i>
                        		<div class="tooltip"><span>linkedin</span></div>
                        		</a>
                        	</li>
                        </ul>
                        วันที่ 29-30 เม.ย. 2560
                      </div>
                  </div>
                  <div class="card-footer">
                      <small>Last updated 3 mins ago</small>
                      <?= $this->tag->linkTo(["activity/show/10", "เพิ่มเติม", "class" => "btn btn-secondary float-right btn-sm"]) ?>
                  </div>
              </div>
          </div>
</div>
