<div class="container">
              <div class="card mt-4">
                  <div class="crop">
                    <img class="card-img-top " src="<?=$this->url->get('img/activity/dotnet.jpg') ?>">
                  </div>
                  <div class="card-block">
                      <figure class="profile">
                          <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" width="30px" class="profile-avatar" alt="">
                      </figure>
                      <h4 class="card-title mt-3">จัดอบรม ScrumWorkshop สำหรับนักศึกษาชั้นปีที่ 1-4</h4>
                      <div class="meta">
                          <a>อาจารย์ ดร.จิตติมา ศังขมณี</a>
                      </div>
                      <div class="card-text">
                        <ul class="mbm_social">
                        	<li><a class="social-facebook" href="#">
                        		<i class="fa fa-facebook"><small>facebook</small></i>

                        		<div class="tooltip"><span>facebook</span></div>
                        		</a>
                        	</li>
                        	<li><a class="social-twitter" href="#">
                        		<i class="fa fa-twitter"><small>Twitter</small></i>
                        		<div class="tooltip"><span>Twitter</span></div>
                        		</a>
                        	</li>
                        	<li><a class="social-google-plus" href="#">
                        		<i class="fa fa-google-plus"><small>google +</small></i>
                        		<div class="tooltip"><span>google</span></div>
                        		</a>
                        	</li>
                        	<li><a class="social-linkedin" href="#">
                        		<i class="fa  fa-linkedin"><small>linkedin</small></i>
                        		<div class="tooltip"><span>linkedin</span></div>
                        		</a>
                        	</li>
                        </ul>
                          เมื่อวันที่ 11-12 มีนาคม 2017 ที่ผ่านมา มีโอกาสไปสอน Agile/Scrum ให้กับน้องๆ ที่ ม.วลัยลักษณ์ เป็นครั้งที่ 2 ประทับใจน้องๆ รุ่นนี้มาก ได้ถ่ายคลิปดีๆ เก็บไว้เยอะเลย ก็เลยอยากทำวิดิโอให้เป็นของขวัญ ดีใจที่มหาวิทยาลัยที่เราจบมา ผลิตศึกษิตที่มีคุณภาพแบบนี้
                        มหาวิทยาลัยไหนสนใจ Workshop แบบนี้ ติดต่อมาได้นะคะ

                      </div>
                  </div>
                  <div class="card-footer">
                      <small>Last updated 3 mins ago</small>
                      <button type="button" class="btn btn-sm btn-outline-primary float-right" data-toggle="modal" data-target="#myModal">จำนวนผู้เข้าร่วม 13/21 คน</button>
                      <!-- Modal -->
                      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              ...
                            </div>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                          </div>
                        </div>
                      </div>

                  </div>
              </div>
          </div>
</div>
