<div class="card mb-4">
  <div class="card-header">
    อาจารย์
  </div>
  <div class="card-block">
    <div class="row">
      <?php for ($i=0; $i < 6; $i++) {
      ?>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-block">
            This is some text within a card block.
          </div>
        </div>
      </div>
      <?php
      } ?>
    </div>
  </div>
</div>
<div class="card mb-4">
  <div class="card-header">
    นักศึกษา
  </div>
  <div class="card-block">
    <div class="row">
      <?php for ($i=0; $i < 6; $i++) {
      ?>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-block">
            This is some text within a card block.
          </div>
        </div>
      </div>
      <?php
      } ?>
    </div>
  </div>
</div>
