<div class="card mb-4">
  <div class="card-header">
    อาจารย์
  </div>
  <div class="card-block">
    <div class="row">
      <?php for ($i=0; $i < 6; $i++) {
      ?>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-block">
            <div class="row">
              <div class="col-md-3">
                <img src="http://www.ruralagriventures.com/wp-content/uploads/2017/05/man-team.jpg" class="rounded float-left" alt="..." width="100%">
              </div>
              <div class="col-md-9">
                <p class="h6"> ผู้ช่วย ชัยสิทธิ์	คุณาปกรณ์การ</p>
                <small>จัดกิจกรรมทั้งหมด 4 กิจกรรม</small>
              </div>
            </div>
          </div>
        </div>
      </div>
      <?php
      } ?>
    </div>
  </div>
</div>
<div class="card mb-4">
  <div class="card-header">
    นักศึกษา
  </div>
  <div class="card-block">
    <div class="row">
      <?php for ($i=0; $i < 6; $i++) {
      ?>
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-block">
            <div class="row">
              <div class="col-md-3">
                <img src="http://www.ruralagriventures.com/wp-content/uploads/2017/05/man-team.jpg" class="rounded float-left" alt="..." width="100%">
              </div>
              <div class="col-md-9">
                <p class="h6"> ผู้ช่วย ชัยสิทธิ์	คุณาปกรณ์การ</p>
                <small>เข้าร่วมกิจกรรมทั้งหมด 2 กิจกรรม</small>
              </div>
            </div>
          </div>
        </div>
      </div>
      <?php
      } ?>
    </div>
  </div>
</div>
