<div class="row">
  <div class="col-md-4">

    <div class="card">
      <div class="card-block card-inverse" style="background-color: #333;">
        <div class="row">
          <div class="col-sm-4">
            <img src="http://www.ruralagriventures.com/wp-content/uploads/2017/05/man-team.jpg" class="rounded float-left" alt="..." width="100%">
          </div>
          <div class="col-sm-8">
            <h4 class="card-title">หฤษฎ์ คงทอง</h4>
            <p class="card-text">ปีการศึกษาที่เข้า พศ.2558</p>
          </div>
        </div>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> เข้าร่วมกิจกรรม : 100% </p>
      </div>


    </div>

    <div class="card mt-4">
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
    </div>

  </div>
  <div class="col-md-8">
    <h2>กิจกรรม <small></small></h2>
    <div class="row">
      <?php for ($i = 0 ; $i<5 ;$i++): ?>
        <div class="col-sm-6 col-md-6 col-lg-6 mt-4">
            <div class="card card-inverse card-info">

                <img class="card-img-top" src="<?=$this->url->get('img/activity/dotnet.jpg') ?>">
                <div class="card-block">
                    <figure class="profile">
                        <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" width="30px" class="profile-avatar" alt="">
                    </figure>
                    <h4 class="card-title mt-3">จัดอบรม .NET for Web-based Application สำหรับนักศึกษาชั้นปีที่ 2</h4>
                    <div class="meta">
                        <a>อาจารย์ ดร.จิตติมา ศังขมณี</a>
                    </div>
                    <div class="card-text">
                      วันที่ 29-30 เม.ย. 2560
                    </div>
                </div>
                <div class="card-footer">
                    <small>Last updated 3 mins ago</small>
                    <?= $this->tag->linkTo(["activity/show/10", "เพิ่มเติม", "class" => "btn btn-secondary float-right btn-sm"]) ?>
                </div>
            </div>
        </div>
      <?php endfor; ?>
    </div>
  </div>
</div>
