<div class="row">
  <div class="col-md-4">
    <?php
      if($user->image == null)
        $user->image = "img/unknown.gif";
     ?>
    <div class="card">
      <div class="card-block card-inverse" style="background-color: #333;">
        <div class="row">
          <div class="col-sm-4">
            <img src="<?=$this->url->get($user->image)?>" width="100%" class="rounded float-left" alt="">
          </div>
          <div class="col-sm-8">
            <?php if ($user->isteacher): ?>
              <p class="card-title"><?=$user->prefix; ?><br><?=$user->Firstname; ?> <?=$user->Lastname; ?></p>
              <p class="card-text"><?=$user->email; ?></p>
            <?php else: ?>
              <p class="card-title"><?=$user->Firstname; ?> <?=$user->Lastname; ?></p>
              <p class="card-text">ชั้นปีการศึกษา : <?=$user->Years;?></p>
                <p class="card-text">รหัสนักศึกษา &nbsp;: <?=$user->username;?></p>
            <?php endif; ?>
          </div>
        </div>
      </div>
      <div class="card-block text-center">
        <?php if ($user->isteacher): ?>
          <center><h4>จำนวนกิจกรรม</h4><h1><?=Activity::find(["teacher_id = ".$user->id])->count()?></h1><h4> กิจกรรม</h4></center>
        <?php else: ?>
          <center><h4>จำนวนกิจกรรมที่เข้าร่วม</h4><h1><?=JoinActivity::find(["joined = 1 and user_id = ".$user->id])->count()?> <small> / </small><?=JoinActivity::find(["user_id = ".$user->id])->count()?></h1><h4> กิจกรรม</h4></center>
        <?php endif; ?>

      </div>
    </div>
  </div>

  <div class="col-md-8">
    <h2>กิจกรรม <small></small></h2>
    <div class="row">
      <?php foreach ($activitys as $activity): ?>
        <?php
          if(isset($activity->activity))
          {
            $activity = $activity->activity;
          }

          if($activity->image == null)
            $activity->image = "img/inf.png";
          if($activity->Teacher->image == null)
            $activity->Teacher->image = "img/unknown.gif";
       ?>
        <div class="col-sm-6 col-md-6 col-lg-6 mt-4">
            <div class="card">

              <img class="card-img-top" src="<?=$this->url->get($activity->image) ?>">
                <div class="card-block">
                    <figure class="profile">
                      <img src="<?=$this->url->get($activity->Teacher->image)?>" width="30px" class="profile-avatar" alt="">
                    </figure>
                    <h4 class="card-title mt-3"><a href="<?=$this->url->get('activity/show/'.$activity->id)?>"><?=$activity->name?></a></h4>
                    <div class="meta">
                        <a class="text-primary"><?=$activity->Teacher->prefix;?>&nbsp;&nbsp;<?=$activity->Teacher->Firstname; ?>&nbsp;&nbsp;<?=$activity->Teacher->Lastname; ?></a>
                    </div>
                    <div class="card-text">
                      <small><?=date("วันที่ d เดือน m  ปี Y",strtotime($activity->StartDate))?> ถึง <?=date("วันที่ d เดือน m  ปี Y",strtotime($activity->EndDate))?></small>
                    </div>
                </div>
                <div class="card-footer">
                    <?= $this->tag->linkTo(['activity/show/'.$activity->id, "เพิ่มเติม", "class" => "btn btn-secondary float-right btn-sm"]) ?>
                </div>
            </div>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
</div>
