<div class="row">
  <div class="col-md-4">

    <div class="card">
      <div class="card-block card-inverse" style="background-color: #333;">
        <div class="row">
          <div class="col-sm-4">
            <img src="http://www.ruralagriventures.com/wp-content/uploads/2017/05/man-team.jpg" class="rounded float-left" alt="..." width="100%">
          </div>
          <div class="col-sm-8">
            <p class="card-title"><?=$user->prefix; ?> <?=$user->Firstname; ?> <?=$user->Lastname; ?></p>
            <p class="card-text"><?=$user->email; ?></p>
          </div>
        </div>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> เข้าร่วมกิจกรรม : 100% </p>
      </div>


    </div>

    <div class="card mt-4">
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
      <div class="card-block text-center">
        <p class="card-text"> ยังไม่รู้จะใส้อะไร </p>
      </div>
    </div>

  </div>
  <div class="col-md-8">
    <h2>กิจกรรม <small></small></h2>
    <div class="row">
      <?php foreach ($activitys as $activity): ?>
        <?php
          if($activity->image == null)
              $activity->image = "img/inf.png";
         ?>
        <div class="col-sm-6 col-md-6 col-lg-6 mt-4">
            <div class="card">

              <img class="card-img-top" src="<?=$this->url->get($activity->image) ?>">
                <div class="card-block">
                    <figure class="profile">
                        <img src="http://success-at-work.com/wp-content/uploads/2015/04/free-stock-photos.gif" width="30px" class="profile-avatar" alt="">
                    </figure>
                    <h4 class="card-title mt-3"><a href="<?=$this->url->get('activity/show/'.$activity->id)?>"><?=$activity->name?></a></h4>
                    <div class="meta">
                        <a class="text-primary"><?=$activity->Teacher->prefix;?>&nbsp;&nbsp;<?=$activity->Teacher->Firstname; ?>&nbsp;&nbsp;<?=$activity->Teacher->Lastname; ?></a>
                    </div>
                    <div class="card-text">
                      <small><?=date("วันที่ d เดือน m  ปี Y",strtotime($activity->StartDate))?> ถึง <?=date("วันที่ d เดือน m  ปี Y",strtotime($activity->EndDate))?></small>
                    </div>
                </div>
                <div class="card-footer">
                    <?= $this->tag->linkTo(["activity/show/10", "เพิ่มเติม", "class" => "btn btn-secondary float-right btn-sm"]) ?>
                </div>
            </div>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
</div>
